<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="0.90.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Toamaisutaa.Core\Toamaisutaa.Core.csproj" />
  </ItemGroup>

</Project>