namespace Toamaisutaa.Abstractions;

/// <summary>
/// Delivers a password an admin caused to exist - typed directly into
/// <see cref="IPasswordAccountService.AdminCreateAccountAsync"/> or
/// <see cref="IPasswordAccountService.AdminSetPasswordAsync"/>, or generated by Toamaisutaa when none
/// was given - to whoever needs it next. The package ships no implementation and no default: what
/// happens to it - a printed credentials sheet, handed over in person, whatever - is not this
/// library's business.
/// </summary>
/// <remarks>
/// Optional, unlike <see cref="IPasswordResetNotifier"/>. Registering one is not required to use
/// local login at all - only to call the two admin-provisioning methods, which resolve this lazily
/// and throw if it is missing rather than failing every application at startup.
/// </remarks>
public interface IAdminPasswordIssuedNotifier
{
    /// <summary>
    /// Called with the raw password, which is the only moment it exists in the clear - the stored
    /// copy is a hash. <b>Never</b> called for a password a person chose for themselves: self-
    /// registration, a self-service change or reset, and completing a reserved invitation never
    /// reach this.
    /// </summary>
    Task PasswordIssuedAsync(ToamaisutaaUser user, string rawPassword, CancellationToken cancellationToken = default);
}
